import express from "express";
import { createTransport } from "nodemailer";
import cors from "cors";
import "dotenv/config";
import { mailConfig } from "./config/mail.ts";

const app = express();
const PORT = process.env.PORT || 3001;

// Simple in-memory rate limiter: 5 requests per 15 minutes per IP
const rateLimitMap = new Map<string, { count: number; resetAt: number }>();
function rateLimiter(req: express.Request, res: express.Response, next: express.NextFunction) {
  const ip = req.ip || "unknown";
  const now = Date.now();
  const windowMs = 15 * 60 * 1000;
  const entry = rateLimitMap.get(ip);
  if (!entry || now > entry.resetAt) {
    rateLimitMap.set(ip, { count: 1, resetAt: now + windowMs });
    return next();
  }
  if (entry.count >= 5) {
    res.status(429).json({ error: "Too many requests, please try again later." });
    return;
  }
  entry.count++;
  next();
}

// Middleware
app.use(cors({ origin: ["http://localhost:5173", "http://localhost:8080", "http://localhost:3000"] }));
app.use(express.json());

// Rate limiting applied to the email endpoint
app.use("/api/send-email", rateLimiter);


// Email transporter
const transporter = createTransport({
  host: mailConfig.host,
  port: mailConfig.port,
  secure: mailConfig.port === 465,
  auth: {
    user: mailConfig.user,
    pass: mailConfig.pass,
  },
});

// POST /api/send-email
app.post("/api/send-email", async (req: express.Request, res: express.Response) => {
  const { name, email, phone, message, page, fields } = req.body;

  try {
    // Basic validation
    if (!name || !email) {
      res.status(400).json({ error: "Name and email are required." });
      return;
    }
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      res.status(400).json({ error: "Invalid email address." });
      return;
    }
    if (!mailConfig.to) {
      res.status(500).json({ error: "Mail recipient is not configured." });
      return;
    }

    const timestamp = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });
    const subject =
      page === "Join"
        ? "New Join Request — IEEE SOU SB"
        : "New Contact Form Submission — IEEE SOU SB";

    // Build email body
    let bodyRows = `
      <tr><td><b>Name</b></td><td>${name}</td></tr>
      <tr><td><b>Email</b></td><td>${email}</td></tr>
      <tr><td><b>Phone</b></td><td>${phone || "—"}</td></tr>
    `;

    // Extra fields from Join form
    if (fields) {
      Object.entries(fields).forEach(([key, value]) => {
        bodyRows += `<tr><td><b>${key}</b></td><td>${value || "—"}</td></tr>`;
      });
    }

    if (message) {
      bodyRows += `<tr><td><b>Message</b></td><td>${message}</td></tr>`;
    }

    bodyRows += `
      <tr><td><b>Page</b></td><td>${page || "Contact"}</td></tr>
      <tr><td><b>Timestamp</b></td><td>${timestamp}</td></tr>
    `;

    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
        <div style="background: #003087; padding: 20px 24px;">
          <h2 style="color: white; margin: 0; font-size: 18px;">IEEE SOU SB — ${subject}</h2>
        </div>
        <div style="padding: 24px;">
          <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
            <tbody style="line-height: 2;">
              ${bodyRows}
            </tbody>
          </table>
        </div>
        <div style="background: #f3f4f6; padding: 12px 24px; font-size: 12px; color: #6b7280;">
          This email was automatically generated by the IEEE SOU SB website.
        </div>
      </div>
    `;

    console.log("Sending email from:", mailConfig.user, "to:", mailConfig.to);
    await transporter.sendMail({
      from: `"IEEE SOU SB Website" <${mailConfig.user}>`,
      to: mailConfig.to,
      replyTo: email,
      subject,
      html,
    });
    res.status(200).json({ success: true, message: "Email sent successfully." });
  } catch (err: any) {
    console.error("Email send error:", err.message || err);
    res.status(500).json({ error: err.message || "Failed to send email. Please try again." });
  }
});

// POST /api/upload - Generic upload endpoint for file uploads
app.post("/api/upload", async (req: express.Request, res: express.Response) => {
  try {
    console.log("Upload endpoint called with body:", req.body);
    
    // If this is a file upload, you would typically use multer or similar middleware
    // For now, we'll handle it as a generic endpoint that can be extended later
    
    // Basic validation
    if (!req.body) {
      res.status(400).json({ error: "No data provided for upload." });
      return;
    }

    // For now, just return a success response
    // In a real implementation, you would:
    // 1. Handle file uploads with multer
    // 2. Validate file types and sizes
    // 3. Store files in cloud storage (AWS S3, Google Cloud, etc.)
    // 4. Return the file URL
    
    res.status(200).json({ 
      success: true, 
      message: "Upload endpoint is ready. Please implement file handling with multer middleware.",
      data: req.body 
    });
  } catch (err: any) {
    console.error("Upload error:", err.message || err);
    res.status(500).json({ error: err.message || "Failed to process upload. Please try again." });
  }
});

app.listen(PORT, () => {
  console.log(`✅ Email server running on http://localhost:${PORT}`);
});
